title: Anton Skrynnik
description: Software Engineer — React Native, Web, Mobile
url: "https://antonjuls.github.io"
baseurl: ""
og_image: /assets/images/avatar.png

markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"
